version: '1'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: 1q2w3e

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  pg-data:
